# Generated by Django 5.0.4 on 2024-04-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('shop_id', models.IntegerField()),
                ('is_customisable', models.BooleanField(default=False)),
                ('attributes', models.JSONField()),
                ('category', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('images', models.JSONField()),
                ('sizes', models.JSONField()),
                ('colours', models.JSONField()),
                ('fabric', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preferred_amount', models.IntegerField()),
                ('preferred_age', models.CharField(max_length=50)),
                ('preferred_season', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Information',
        ),
    ]
